create table tbinstrutores (id integer not null auto_increment,
nome varchar(255),
email varchar(255),
edv varchar(255),
curso varchar (255),
disciplina varchar(255),
trilha varchar(255),
faculdade varchar(255),
turma varchar(255),
primary key (id));
